name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-typecheck-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ./frontend
        
    - name: Lint the project
      run: yarn lint
      working-directory: ./frontend

    - name: Typecheck the project
      run: npx tsc --noEmit
      working-directory: ./frontend

    - name: Run tests
      run: yarn test:unit
      working-directory: ./frontend